<?php

namespace Id2i\Core\PlacementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlacementTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacementTypeRepository extends EntityRepository
{
}
