media_superadmin_media:
    resource: "@MediaBundle/Resources/config/routing/media.yml"
    prefix:   /superadmin/media
media_front:
    resource: "@MediaBundle/Resources/config/routing/media_front.yml"
    prefix:   /
media_ajax_choice:
    path:     /media/ajax/choice/{id}/{options}
    defaults: { _controller: MediaBundle:Ajax:choice }
media_ajax_upload:
    path:     media/ajax/upload
    defaults: { _controller: MediaBundle:Ajax:upload }
