services:
    id2i.tools.csvTreatment:
        class: Id2i\Tools\ServiceBundle\Service\CsvTreatment
#    service.example:
#        class: Id2i\Tools\ServiceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    droits.service:
        menu:
            show: false
        back:
            show: false
            add: false
#           all_edit: false
#           owner_edit: false
#           all_delete: false
#           owner_delete: false
            edit: false
            delete: false
        front:
            show: false
            add: false
            edit: false
            delete: false


