<?php

namespace Id2i\CMS\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageEtatRepository extends EntityRepository
{
}
