<?php

namespace Id2i\Tools\PubliciteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PubliciteStatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubliciteStatistiqueRepository extends EntityRepository
{
}
