services:
#    cms.example:
#        class: Id2i\Core\CMSBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
  droits.cms:
      menu:
        view: false
  droits.page:
      back:
        read: false
        new: false
        edit: false
        delete: false
        validate: true
      front:
        read: true
        new: true
        edit: true
        delete: true
#gestion pulti site (avec un ecouteur d'evenement)



