services:
#    publicite.example:
#        class: Id2i\Tools\PubliciteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    droits.publicite:
        menu:
            view: false
        back:
            show: false
            add: false
#           all_edit: false
#           owner_edit: false
#           all_delete: false
#           owner_delete: false
            edit: false
            delete: false
        front:
            show: false
            add: false
            edit: false
            delete: false


