services:
#    user.example:
#        class: Id2i\Core\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
  droits.user:
      back:
        read: false
        new: false
        export_csv: false
        edit: false
        delete: false
      front:
        read: true
        new: true
        edit: true
        delete: true