<?php

namespace Id2i\Core\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaMetaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaMetaDataRepository extends EntityRepository
{
}
