<?php

namespace Id2i\Core\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('bundle' => 'ASC'));
    }
}
