commune:
    path:     /
    defaults: { _controller: "CommuneBundle:Commune:index" }

commune_show:
    path:     /{id}/show
    defaults: { _controller: "CommuneBundle:Commune:show" }

commune_new:
    path:     /new
    defaults: { _controller: "CommuneBundle:Commune:new" }

commune_create:
    path:     /create
    defaults: { _controller: "CommuneBundle:Commune:create" }
    requirements: { _method: post }

commune_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommuneBundle:Commune:edit" }

commune_update:
    path:     /{id}/update
    defaults: { _controller: "CommuneBundle:Commune:update" }
    requirements: { _method: post|put }

commune_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommuneBundle:Commune:delete" }
    requirements: { _method: get|post|delete }
