parameters:
  services_root: Id2i\Core\MediaBundle\Services
  form_root: Id2i\Core\MediaBundle\Form
  droits.media:
    back:
      read_his: true
      read_all: false
      create: true
      delete_his: true
      delete_all: false

services:
  media:
    class: %services_root%\Media
  media.form.type.media:
    class: %form_root%\Type\MediaType
    tags:
      - { name: form.type, alias: media }

