<?php

namespace Id2i\Ecommerce\DocumentVenteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentVenteRepository extends EntityRepository
{
}
